$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    pagination:false,
    autoplay:1500,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})